#+TITLE: My Dotfiles

This directory contains dotfiles for my MacOS and Linux systems.

* Requirements
The only required pieces of software are =git= and =stow=.

#+BEGIN_SRC sh
# Arch linux
sudo pacman -S git stow

# MacOS
brew install git stow
#+END_SRC

* Installation
Check out this repo in your =$HOME= directory using git
#+BEGIN_SRC sh
cd ~
git clone https://github.com/tkim288a1/dotfiles.git
cd dotfiles
#+END_SRC
and then use GNU stow to create symlinks
#+BEGIN_SRC sh
stow .
#+END_SRC

* Remarks on Emacs Configuration
My Emacs configuration is located in the ~/.config/taemax directory. I frequently experiment with different Emacs profiles. To make switching between configurations more convenient, I use [[https://github.com/plexus/chemacs2?tab=readme-ov-file#installation][Chemacs2]]. Below is a summary of the setup process:

My emacs configuration is located in the =~/.config/taemax= directory. I frequently experiment with different Emacs profiles. To make switching between configurations more convenient, I use [[https://github.com/plexus/chemacs2?tab=readme-ov-file#installation][Chemacs2]]. Below is a summary of the setup process:

1. Backup Existing Configuration:

   If the =~/.emacs.d= directory already exists, move it to a backup location.
   
2. Install Chemacs2:

   Clone the Chemacs2 repository into the =~/.emacs.d= directory:
   #+begin_src sh
   $ git clone https://github.com/plexus/chemacs2.git ~/.emacs.d
   #+end_src
   
3. Create a Profiles File:

   Define Emacs profiles in the =~/.emacs-profiles.el= file. For example:

   #+begin_src emacs-lisp
     (("default" . ((user-emacs-directory . "~/.config/taemax")))
      ("prelude" . ((user-emacs-directory . "~/path/to/prelude-profile")))
      ("test" . ((user-emacs-directory . "~/path/to/test-profile")))
      )   
   #+end_src

** Switching between Profiles
By default, Emacs uses the profile named =default=. To switch to a different profile, create or update the =~/.emacs-profile= file. For example:

#+begin_src sh
$ echo 'prelude' > ~/.emacs-profile  
#+end_src

** TODO A separate git repo for emacs config
Consider moving emacs configuration to a separate git repo as it grows over time. 
